version: '{branch}-{build}'
before_build:
- cmd: >-
    nuget restore CSF.MicroDi.sln
    
    nuget install NUnit.ConsoleRunner -Version 3.6.1 -OutputDirectory testrunner
    
    nuget install NUnit.Extension.NUnitV2Driver -Version 3.6.0 -OutputDirectory testrunner

build:
  verbosity: minimal
test_script:
- cmd: testrunner\\NUnit.ConsoleRunner.3.6.1\\tools\\nunit3-console.exe CSF.MicroDi.Tests\\bin\\Debug\\CSF.MicroDi.Tests.dll CSF.MicroDi.BoDiCompatibility.Tests\\bin\\Debug\\CSF.MicroDi.BoDiCompatibility.Tests.dll CSF.MicroDi.BoDiCompatibility.IntegrationTests\\bin\\Debug\\BoDi.Tests.dll --result=myresults.xml