language: csharp
solution: CSF.MicroDi.sln

install:
  - nuget restore CSF.MicroDi.sln
  - nuget install NUnit.ConsoleRunner -Version 3.6.1 -OutputDirectory testrunner
  - nuget install NUnit.Extension.NUnitV2Driver -Version 3.6.0 -OutputDirectory testrunner
  - cp testrunner/NUnit.Extension.NUnitV2Driver.3.6.0/tools/* testrunner/NUnit.ConsoleRunner.3.6.1/tools/

script:
  - msbuild /p:Configuration=Debug CSF.MicroDi.sln
  - mono "./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe" CSF.MicroDi.Tests/bin/Debug/CSF.MicroDi.Tests.dll CSF.MicroDi.BoDiCompatibility.Tests/bin/Debug/BoDi.Tests.dll